"""
Generate the weights for each models with OLS (ordinary least square) regression:

Let X be a set of predictions generated by different models,
    β be the weights,
    y be the ground truth.

To minimize least square error (y - Xβ)ᵀ(y - Xβ),
    β = (XᵀX)^-1 Xᵀy 

"""
import numpy as np

def get_weights(X: np.array, y: np.array) -> np.array:
    """Compute weights for each prediction

    Arguments:
        X: #models × #predictions -- predictions generated by each models
        y: #predictions           -- ground truth (test sets)

    Return:
        weights: #models -- weights for each model. Predictions @ weights gives the 
            blended predictions 
    """
    w = np.linalg.inv(X @ X.T) @ X @ y
    return w

